baseURL = "https://blog.rouages.xyz"
theme = "rouages"
title = "~adrien"
languageCode = "en-us"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy 2020"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 2

[params]
  description = "Your meta description"
  header_title = "~adrien"
  header_subtitle = "Tech stuff! "
  recent_posts = 5
  mainSections = ["articles"]
  [params.style]
    backgroundColor = "#f8f9fa"
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = "http://github.com/radium226"
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://fr.linkedin.com/public-profile/in/adrienbesnard"